### PR TITLE
Switch pusher client library

### PR DESCRIPTION
**Pull request by jinseokoh**
Pusher client library included in the last commit [6778b97](https://github.com/kakajansh/echo/commit/6778b972476df428ce5f9de28cbd5545f4c04fca) didn't work for me. This PR basically switches the client library from [flutter_pusher_client](https://github.com/heywhy/flutter-pusher-client) to [pusher_websocket_flutter](https://github.com/HomeXLabs/pusher-websocket-flutter) and updates Pusher related logic to adopt the new Pusher library.

I've also updated `/example/lib` sample code for Pusher, where you can test out public/private channel communication. Even if you haven't set up Laravel broadcast auth configuration, you'd have no problem receiving broadcast event when using public channel.

### CODE REVIEW

**Comment by combi-35** [comment]
Do you know how I can use your PR with laravel websocket package beyondcode? I included your PR to my flutter dependencies, but I can't get a connection to the websocket. 
I just have a public Event without auth.

**Comment by chinloyal** [comment]
@jinseokoh @combi-35 You can just use ([pusher_client](https://pub.dev/packages/pusher_client)) works perfectly with this plugin. It also has client events and encrypted channels fully  implemented for android and ios.

**Comment by AndreasElia** [comment]
It seems the `pusher_websocket_flutter` package is archived and no longer maintained?

**Comment by MahdiPishguy** [comment]
> `pusher_websocket_flutter`

yes that's right

**Comment by AndreasElia** [comment]
> > `pusher_websocket_flutter`
> 
> yes that's right

Worth closing this issue then, I'd assume @kakajansh.

**Comment by kakajansh** [comment]
Closed as `pusher_websocket_flutter` is archived and no longer maintained.

**Pull request closed without merging**
