### PR TITLE
migrate to null safety support

### PR DESCRIPTION
**Pull request by RizalMuhamadH**

### CODE REVIEW

**Review by alphaolomi — APPROVED** [review]

**Comment by Tumist76** [comment]
Somebody merge this please!

**Comment by MahdiPishguy** [comment]
+۱

**Comment by AymanMubark** [comment]
+1

**Comment by AymanMubark** [comment]
+1

**Comment by kakajansh** [comment]
Thank you for your contributions. New version was released with support of null-safety.

**Pull request closed without merging**
